package JardinCollectif.repositories.helpers;

import java.lang.reflect.Field;

public class ColumnHelper {
    private String name;
    private boolean primary;
    private boolean autoGenerated;
    private Field field;

    public ColumnHelper(String name, boolean primary, boolean autoGenerated, Field field) {
        this.name = name;
        this.primary = primary;
        this.autoGenerated = autoGenerated;
        this.field = field;
    }

    public String getName() {
        return name;
    }

    public boolean isPrimary() {
        return primary;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public Field getField() {
        return field;
    }
}