package JardinCollectif.repositories.helpers;

import java.lang.reflect.Field;

public class ColumnHelper {
  private final String name;
  private final boolean primary;
  private final boolean autoGenerated;
  private final Field field;

  public ColumnHelper(String name, boolean primary, boolean autoGenerated, Field field) {
    this.name = name;
    this.primary = primary;
    this.autoGenerated = autoGenerated;
    this.field = field;
  }

  public String getName() {
    return name;
  }

  public boolean isPrimary() {
    return primary;
  }

  public boolean isAutoGenerated() {
    return autoGenerated;
  }

  public Field getField() {
    return field;
  }
}