package JardinCollectif.repositories.helpers;

import JardinCollectif.IFT287Exception;
import JardinCollectif.annotations.Column;
import JardinCollectif.annotations.Entity;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

public class TableHelper {
  private final String tableName;
  private final List<ColumnHelper> columns;
  private final List<ColumnHelper> primaryKey;

  public TableHelper(Class entityType) throws IFT287Exception {
    Entity table = (Entity) entityType.getAnnotation(Entity.class);
    tableName = table.value().equals("") ? entityType.getSimpleName() : table.value();

    columns = new ArrayList<>();
    primaryKey = new ArrayList<>();
    for (Field field : entityType.getFields()) {
      Column column = field.getAnnotation(Column.class);
      if (column != null) {
        String columnName = column.name().equals("") ? field.getName() : column.name();
        ColumnHelper columnHelper = new ColumnHelper(columnName, column.primaryKey(), column.autoGenerated(),
                field);
        columns.add(columnHelper);
        if (column.primaryKey()) {
          primaryKey.add(columnHelper);
        }
      }
    }

    if (primaryKey.isEmpty()) {
      throw new IFT287Exception("Entity should have a primary key.");
    }
  }

  public List<ColumnHelper> getColumns() {
    return columns;
  }

  public String getTableName() {
    return tableName;
  }

  public List<ColumnHelper> getPrimaryKey() {
    return primaryKey;
  }
}
