package JardinCollectif.model;

import java.util.Date;

import org.bson.Document;
import org.bson.types.ObjectId;

import JardinCollectif.annotations.Column;
import JardinCollectif.annotations.Entity;
import JardinCollectif.annotations.Initializer;

@Entity
public class IsSowedIn {
  @Column(primaryKey = true, autoGenerated = true, name = "_id")
  public ObjectId isSowedInId;
  @Column
  public long quantity;
  @Column
  public long memberId;
  @Column
  public Date plantingDate;
  @Column
  public String plantName;
  @Column
  public String lotName;

  @Initializer
  public IsSowedIn(Document d) {
    this.isSowedInId = d.getObjectId("_id");
    this.quantity = d.getLong("quantity");
    this.memberId = d.getLong("memberId");
    this.plantingDate = (Date) d.getDate("plantingDate");
    this.plantName = d.getString("plantName");
    this.lotName = d.getString("lotName");
  }

  public IsSowedIn(long quantity, Date plantingDate, long memberId, String lotName, String plantName) {
    this.quantity = quantity;
    this.memberId = memberId;
    this.plantingDate = plantingDate;
    this.plantName = plantName;
    this.lotName = lotName;
  }
}