package JardinCollectif.model;

import java.sql.Date;

import JardinCollectif.annotations.Column;
import JardinCollectif.annotations.Entity;

@Entity
public class IsSowedIn {
  @Column(primaryKey = true, autoGenerated = true)
  public int isSowedInId;

  @Column
  public int quantity;

  @Column
  public int memberId;

  @Column
  public Date plantingDate;

  @Column
  public String plantName;

  @Column
  public String lotName;

  public IsSowedIn(int isSowedInId, int quantity, Date plantingDate, int memberId, String lotName, String plantName) {
    this.isSowedInId = isSowedInId;
    this.quantity = quantity;
    this.memberId = memberId;
    this.plantingDate = plantingDate;
    this.plantName = plantName;
    this.lotName = lotName;
  }
}